// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EngineEnabled() {
  return window['go']['main']['App']['EngineEnabled']();
}

export function EngineRunning() {
  return window['go']['main']['App']['EngineRunning']();
}

export function GetAutostart() {
  return window['go']['main']['App']['GetAutostart']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function PreviewScript() {
  return window['go']['main']['App']['PreviewScript']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['main']['App']['SetAutostart'](arg1);
}

export function SetEnabled(arg1) {
  return window['go']['main']['App']['SetEnabled'](arg1);
}

export function ToggleEnabled() {
  return window['go']['main']['App']['ToggleEnabled']();
}
