// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';
import {main} from '../models';

export function EngineEnabled():Promise<boolean>;

export function EngineRunning():Promise<boolean>;

export function GetAutostart():Promise<boolean>;

export function GetConfig():Promise<model.Config>;

export function GetState():Promise<main.State>;

export function PreviewScript():Promise<string>;

export function SaveConfig(arg1:model.Config):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetEnabled(arg1:boolean):Promise<void>;

export function ToggleEnabled():Promise<boolean>;
